/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d8d77ac9-c788-48f4-acd7-aae67277cf79",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_xpXu8DLhS",
    "aws_user_pools_web_client_id": "5sq2imslart75tdsur9v7csqg8",
    "oauth": {},
    "aws_cognito_login_mechanism": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_appsync_graphqlEndpoint": "https://lchocpaoynhg3jwnou25okamxy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rrmtn73lwfgbbiyagfms34zhqa",
    "aws_content_delivery_bucket": "amplifyapp-20210810134048-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://amplifyapp-20210810134048-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
